### ISSUE TITLE
Ability to Save Schedules

### ISSUE THREAD

**Issue by rosstex** [mDibyo/berkeley-scheduler#12]
I requested this on the SIS scheduler, and I think it'd be very helpful on yours as well! You should be able to save potential schedules in a list.

**Comment by mDibyo** [comment]
Currently, if you wanna do this, you can copy the url of the page for the schedules you are interested in saving. If you go back to the same url, you will have your schedule back.
Of course, this is not super convenient. So, will add this ability to the website itself..

**Comment by rosstex** [comment]
I can definitely do that meanwhile, thanks!

**Comment by mDibyo** [comment]
Done.

**Comment by mDibyo** [comment]
This feature is not yet perfect since it assumes that the same courses are present in all the schedules. But the resolution for #14 should get rid of that assumption.
