### ISSUE TITLE
Missing some classes?

### ISSUE THREAD

**Issue by angela-ko** [mDibyo/berkeley-scheduler#13]
Idk which ones, but you're missing Cog Sci C100? (I know it exists cause I phase 1-ed it :O)

**Comment by mDibyo** [comment]
So, on searching for all courses from the official database, only COG SCI 100 shows up. However, the database says that 'COG SCI 100' is not being offered next semester, but 'COG SCI C100' is. Has this course been cross-listed only recently? What's it cross-listed with?

**Comment by priyamdas** [comment]
The course has traditionally been cross-listed with Psychology C120

**Comment by mDibyo** [comment]
I investigated this further, and couldn't find a systemic cause for this. I have manually added COG SCI C100 to my API crawling pipeline, so it will now be listed. But I can't be sure if there are other classes missing.

Closing this issue for now, but will reopen it if we find more classes missing.
