### ISSUE TITLE
Add option to select or unselect classes for schedule generating

### ISSUE THREAD

**Issue by nuckollsk** [mDibyo/berkeley-scheduler#14]
It would be really nice to have the ability to select a subset of classes from a list of what I might end up taking next semester and generate schedules with this subset. I'm not exactly sure what I will take next semester, so this option could help me see some possible schedules. Thanks man!

**Comment by mDibyo** [comment]
This is an important feature too. Will work on this.

**Comment by mDibyo** [comment]
Done!
