### ISSUE TITLE
See Final Exam Schedule

### ISSUE THREAD

**Issue by nuckollsk** [mDibyo/berkeley-scheduler#15]
This would be a game changer. Right now, the process to find out when your final exam is held and whether or not you have classes that conflict with their finals is quite inconvenient. The information is all there, held in a table here: http://schedule.berkeley.edu/examf.html However, if your page could automatically check the data in this table and output an exam schedule, that would be amazing!

**Comment by mDibyo** [comment]
You are right about that! Its easy to add it, and it would be an awesome addition. On it.

**Comment by nuckollsk** [comment]
That would be insane. I feel like there a lot of people who are currently signing up for classes with conflicting finals. Your site could help stop them from quite a lot of stress come the end of next semester. Thanks for reading my feedback!

**Comment by virajmahesh** [comment]
+1

**Comment by mDibyo** [comment]
Done! Finals Schedule now shows up above the schedule.

**Comment by nuckollsk** [comment]
Looks great! My only suggestion is to change the appearance of the button. Right now, it looks a bit like a title instead of a clickable option.

**Comment by mDibyo** [comment]
That's a good point. I will make the change.
Also, reopen the issue when you are not happy with its resolution. (It makes it easier to see what needs work. :) )

**Comment by nuckollsk** [comment]
Sorry man, will do next time

**Comment by mDibyo** [comment]
Thanks for taking the time to find issues! :)
Done. (Let me know if you don't like the styling. I am not completely sure its the best choice. )
