### ISSUE TITLE
crashes on chrome when i click get schedules

### ISSUE THREAD

**Issue by SahilSancheti** [mDibyo/berkeley-scheduler#18]

**Comment by mDibyo** [comment]
This is probably happening because the number of schedules that was being generated was too large. Did you add a lot of classes, or classes with many sections?

If this is indeed the problem, a fix is coming soon.

**Comment by SahilSancheti** [comment]
That seems to be the issue

**Comment by mDibyo** [comment]
Fixed! Sorry for the long wait; the fix was quite involved.

EDIT: To add more context to this, schedule generation is now done in the background, and you can do other stuff while its happening. The browser no longer thinks the webpage is stuck.

Please reopen the issue if this is still a problem.
