### ISSUE TITLE
Show section numbers, e.g. LEC 001, DIS 104

### ISSUE THREAD

**Issue by hibachrach** [mDibyo/berkeley-scheduler#20]

**Comment by mDibyo** [comment]
So FYI, this information is not currently getting propagated from the API to my class model. I will have to investigate the problem and recrawl the API, so putting this into the weekend sprint.

**Comment by hibachrach** [comment]
Gotcha. Thanks for the continued work, man.

**Comment by mDibyo** [comment]
Done. Sorry it took so long (was a simple fix).
