### ISSUE TITLE
Add an option to allow only unavoidable conflicts (or minimize conflicts)

### ISSUE THREAD

**Issue by virajmahesh** [mDibyo/berkeley-scheduler#22]
Right now, if you allow conflicts to happen, the system allows all kinds of conflicts to take place, including ones that are not necessary.

The minimization doesn't need to be perfect. Even something that orders schedules by number of conflicts would be perfect for getting rid of unnecessary conflicts.

**Comment by mDibyo** [comment]
Yeah. That's a good idea. On it.

**Comment by mDibyo** [comment]
Done.
