### ISSUE TITLE
Exam time appears to be wrong for CS169

### ISSUE THREAD

**Issue by ollie-o** [mDibyo/berkeley-scheduler#31]
Lecture is Tu-Th 9:30am, so according to http://schedule.berkeley.edu/examf.html the final exam should be Tuesday 3:00pm to 6:00pm.

In the final exam calendar it has it as 3:00pm to 6:00pm Thursday.

**Comment by rosstex** [comment]
thanks

**Comment by mDibyo** [comment]
@rosstex thanks for the ping!
I have confirmed the problem, and found the bug. I will fix it today evening.

**Comment by mDibyo** [comment]
Fixed.
