### ISSUE TITLE
Incorrect final time slots

### ISSUE THREAD

**Issue by goods-consumer** [mDibyo/berkeley-scheduler#39]
Music 158A Lecture 2 is TuTh 11-12:29. According to the [final exam calendar](http://schedule.berkeley.edu/examf.html), its final is Wednesday 8-11 AM. However, the scheduler shows it as Tuesday 3-6 PM.

**Comment by mDibyo** [comment]
The confusion seems to be caused by the fact that there are two lecture sections for the class. (The other section is TuTh 9:30-10:59 which would have a final time slot of Tuesday 3-6 PM. ) I will investigate this further and fix it. Sorry for the confusion!

**Comment by mDibyo** [comment]
This is related to #71.

**Comment by mDibyo** [comment]
Done in #86.
