### ISSUE TITLE
Cannot generate schedules for first time users

### ISSUE THREAD

**Issue by tiffanyqi** [mDibyo/berkeley-scheduler#41]
A first time user does this:
1. Add classes in the lefthand column
2. Selects "generate schedule"
3. Nothing is generated.

Is fixed when sent a link to a schedule result, but this probably isn't the best way to get around this problem.

**Comment by mDibyo** [comment]
Haha, yeah! :D 

Thanks for finding this one! Will investigate further.

**Comment by mDibyo** [comment]
I think I found the reason for this happening. (for first time users, no data has yet been stored in cookies, and in that case, Berkeley Scheduler was putting in the wrong default value.)

Please reopen if this is still a problem.
