### ISSUE TITLE
Final exam conflicts do not show properly

### ISSUE THREAD

**Issue by tiffanyqi** [mDibyo/berkeley-scheduler#42]
Way to reproduce:
1. Select CS 61A from the dropdown menu
2. Select Psych 1, a class that conflicts with CS 61A
3. View overlapping conflict, but only see "CS 61A" at the timeslot

![13941025_10154346766356054_1678745051_n](https://cloud.githubusercontent.com/assets/6607768/17563507/9e51ab98-5ee4-11e6-8e85-c28e24c108bc.png)

**Comment by mDibyo** [comment]
Displaying time-conflicting finals in the same way as conflicting sections in the schedule is probably the best solution here. Targeting this for the upcoming release.

**Comment by mDibyo** [comment]
Done!
