### ISSUE TITLE
CS 61A Lab does not comprise the full time

### ISSUE THREAD

**Issue by tiffanyqi** [mDibyo/berkeley-scheduler#43]
Way to reproduce:
1. Select CS 61A from the dropdown
2. Prefer mornings
3. Generate schedule
4. View the very thin sliver that is CS 61A Lab, when it should be three lines

![screen shot 2016-08-10 at 10 25 04 am](https://cloud.githubusercontent.com/assets/6607768/17563583/e545b86e-5ee4-11e6-83bf-83aba1b9952e.png)

**Comment by mDibyo** [comment]
This is a problem propagating from the data received from the SIS API. (the lab has a half-an-hour timeslot officially. ) So, can't fix this in Berkeley Scheduler.
