### ISSUE TITLE
Generating schedules doesn't work for select courses

### ISSUE THREAD

**Issue by tiffanyqi** [mDibyo/berkeley-scheduler#46]
To reproduce:
1. Select "econ 1"
2. Generate schedules

No schedules are generated. Javascript console says: lib.min.js:13 TypeError: Cannot read property 'days' of undefined

May be due to the fact that econ 1 is a course exception, and may not have a "days" property.

**Comment by tiffanyqi** [comment]
Also breaks everything, can't generate schedules anymore :(

**Comment by mDibyo** [comment]
Turns out this was not a problem with Finals, but with section times. ECON 1 DIS 123 has no time/location set. The scheduler was tripping up on that. Am now accounting for that.
