### ISSUE TITLE
Missing courses: EPS C162 And INFO 152

### ISSUE THREAD

**Issue by Nsrose** [mDibyo/berkeley-scheduler#47]
I think the schedule is missing Earth & Planetary Sciences C162.

**Comment by rosstex** [comment]
Also Info 152

**Comment by mDibyo** [comment]
Both problems confirmed. Thanks for reporting guys!

Investigating this further.

**Comment by mDibyo** [comment]
@Nsrose What class is EPS C162 cross-listed with?

@Nsrose and @rosstex Have these classes been recently added?

**Comment by rosstex** [comment]
EPS C162 is also Astronomy C162. I'm not sure when they were added.

**Comment by mDibyo** [comment]
EPS C162 has been added. INFO 152 is not available on the SIS API. Not sure what's going on there. Investigating further.

**Comment by mDibyo** [comment]
Closing this, as it is no longer relevant. Follow progress on #38.
