### ISSUE TITLE
Selecting no courses breaks rest of schedule generation

### ISSUE THREAD

**Issue by tiffanyqi** [mDibyo/berkeley-scheduler#48]
1. Select no courses
2. Press generate
3. Select another course, is frozen, and can no longer breaks again until a refresh. Some messaging around this would be good.

**Comment by mDibyo** [comment]
Have been able to reproduce this. Should be easy to fix.

**Comment by mDibyo** [comment]
Fixed. Please reopen if you find a case where this is failing.
