### ISSUE TITLE
Better display for scheduling options

### ISSUE THREAD

**Issue by tiffanyqi** [mDibyo/berkeley-scheduler#50]
Sorting categories (preferred time of day, gaps, days, prefer no conflicts) to be distinguished from filtering categories (no conflicts and time restrictions), and should be explicitly mentioned that you can only sort by one selected category.

**Comment by mDibyo** [comment]
This is more or less done. I have not explicitly added that only one sorting option can be selected. Do you think it should be added?
![image](https://cloud.githubusercontent.com/assets/4902438/17579323/edc6cc8a-5f48-11e6-8fef-0733958057c6.png)

**Comment by mDibyo** [comment]
Now added that too.
![13931706_10209074822059412_1635488513_o](https://cloud.githubusercontent.com/assets/4902438/17829071/871a8b06-6656-11e6-9423-2a4f5c346844.png)

Closing. Please reopen if you think it could be made better.

**Comment by mDibyo** [comment]
I forgot to separate out the Filtering options. Here's the updated version:
![image](https://cloud.githubusercontent.com/assets/4902438/17829832/d5b4ac06-666f-11e6-8ba6-9be1c3be5271.png)
