### ISSUE TITLE
No Courses Found

### ISSUE THREAD

**Issue by pmespresso** [mDibyo/berkeley-scheduler#54]
<img width="233" alt="default" src="https://cloud.githubusercontent.com/assets/10432070/18568962/c06d083a-7b54-11e6-9b95-fdf430151e82.png">

This seems to happen with every class I try to add.

**Comment by mDibyo** [comment]
This has been fixed. Sorry for taking so long to fix it. :(

I have added some [tests](https://github.com/mDibyo/berkeley-scheduler/blob/c937d972662596b771428a6d245f87e7397fde7d/data/src/tests/test_final_dir.py) to track this problem in future.

Please reopen if this is still a problem.
