### ISSUE TITLE
Spring 2017 Schedule

### ISSUE THREAD

**Issue by rosstex** [mDibyo/berkeley-scheduler#55]
It's upon us!

**Comment by mDibyo** [comment]
Thought I did it a few hours ago (https://github.com/mDibyo/berkeley-scheduler/commit/49ec5693b525dd54fffc10496e281268818c4f32) but there seems to be a bug.

Looking into it.

**Comment by mDibyo** [comment]
Related to #54.

**Comment by mDibyo** [comment]
Done. Finals schedule has not been added yet, creating separate issue for it.

**Comment by mDibyo** [comment]
Finals schedule also added!
