### ISSUE TITLE
Nutrisci 108A Bug

### ISSUE THREAD

**Issue by holycow450** [mDibyo/berkeley-scheduler#58]
The class time for Nutrisci 108A is listed as 12am-12am.

**Comment by mDibyo** [comment]
Looking into this now.

**Comment by mDibyo** [comment]
Turns out, Nutrisci 108A is one of many classes that are listed as available for Spring 2017, but aren't really being offered. In future, these classes will not appear in the search results.

**Comment by mDibyo** [comment]
Done! All classes that are not being offered next semester have been removed.
