### ISSUE TITLE
Difficult to figure out that the course was added

### ISSUE THREAD

**Issue by virajmahesh** [mDibyo/berkeley-scheduler#6]
![screen shot 2016-04-27 at 7 10 01 pm](https://cloud.githubusercontent.com/assets/779731/14873467/abfd8694-0cab-11e6-8161-73fcf36ff0f9.png)

Right now it just adds the course by default. It's also not intuitive that you have to click the X's to select new courses. You could either:
- Have an 'Add Course' button that adds the course to your schedule when you click it and then clears out the course selection fields
- Just clear out the course selection fields automatically. This tells the user that the action they were trying to do has been completed. This is what ScheduleBuilder does.

**Comment by mDibyo** [comment]
I like the second option. Should be easier to add.
