### ISSUE TITLE
IB C32 missing

### ISSUE THREAD

**Issue by zhengzhu88** [mDibyo/berkeley-scheduler#67]
It's being offered in Spring 2017 but it doesn't show up on the list. It's cross-listed as L&S C30Z.
https://ib.berkeley.edu/undergrad/courses/curriculum.php

**Comment by mDibyo** [comment]
Issue confirmed. Investigating.

**Comment by mDibyo** [comment]
@zhengzhu88 Hey!

**Comment by mDibyo** [comment]
This is now resolved in #86.
