### ISSUE TITLE
Support common acronyms for departments

### ISSUE THREAD

**Issue by virajmahesh** [mDibyo/berkeley-scheduler#7]
'EE' for EL ENG
'CS' for COMP SCI

'PS' for 'POL SCI'
'PP' for 'PUB POL'

Can't think of any others but I'm sure there are some.

**Comment by mDibyo** [comment]
Some others I found:
PE for 'POL ECON'
NST for 'NUSCTX'

**Comment by mDibyo** [comment]
Done.
