### ISSUE TITLE
Lectures and labs aren't matched properly

### ISSUE THREAD

**Issue by KaitoKid** [mDibyo/berkeley-scheduler#71]
Currently, some labs are available to specific lectures. Need to adjust schedules so they don't get these mixed up

Schedule generated by BerkeleyScheduler: http://i.imgur.com/4LvYNkl.png

Actual available options: http://i.imgur.com/umvKUDy.png

**Comment by mDibyo** [comment]
This is a big data problem. Prioritizing this.

**Comment by mDibyo** [comment]
Done.
