### ISSUE TITLE
Schedule Rendering Misaligned

### ISSUE THREAD

**Issue by rosstex** [mDibyo/berkeley-scheduler#76]
The hour slots slowly drag behind the class layout.

![189 is off the charts!](https://puu.sh/rNl6v/c7a964f220.png)

**Comment by mDibyo** [comment]
:O
I might have fixed that. Can you try rendering this again?

**Comment by rosstex** [comment]
Unfortunately not fixed yet! Thanks for looking into this

**Comment by mDibyo** [comment]
Finally fixed! Sorry for the slow fix. :|

Please reopen if this is still an issue.
