### ISSUE TITLE
Missing Physics 7B?

### ISSUE THREAD

**Issue by khoslaventures** [mDibyo/berkeley-scheduler#78]
Hey, great schedule builder. Noticed that you were missing Physics 7B. Would you mind adding that in?

**Comment by mDibyo** [comment]
Hey! Thanks!

Also thanks for taking the time to report this. Physics 7B seems to be available currently. It might have been unavailable for a brief period of time, not sure what went wrong.

I am closing this issue. Please reopen if you run into this problem again.

**Comment by khoslaventures** [comment]
Awesome, thanks for the support!
