### ISSUE TITLE
Export schedule as calendar does not work

### ISSUE THREAD

**Issue by mudit2103** [mDibyo/berkeley-scheduler#83]
Hi,

The export schedule as calendar button does not do anything. I only added CS170 and the corresponding 101 discussion. There appears to be a typeerror on clicking on the export schedule button. For reference, here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/12883092/21826059/85cec658-d79f-11e6-8187-4d21f4f13186.png)

**Comment by mDibyo** [comment]
Thanks for the bug report and the screenshot. This has been fixed now! :)

Please reopen if you face any other issues.
