### ISSUE TITLE
Some of the colors are too hard to read

### ISSUE THREAD

**Issue by virajmahesh** [mDibyo/berkeley-scheduler#9]
![screen shot 2016-04-27 at 7 27 04 pm](https://cloud.githubusercontent.com/assets/779731/14873724/13eb2bba-0cae-11e6-95fe-95efdbc524fd.png)

**Comment by mDibyo** [comment]
I have changed the text color to black. I think that makes it more legible.

Could you take a look?

**Comment by virajmahesh** [comment]
LGTM 👍

**Comment by mDibyo** [comment]
Closing.
