### ISSUE TITLE
Alphabetical sorting of event/ class list

### ISSUE THREAD

**Issue by CPLuu** [mDibyo/berkeley-scheduler#94]
I usually add a number of classes to compare the potential schedules. However, in this case, the list on the left sidebar gets burdensome to look through and select/ unselect classes. One solution is to sort the items alphabetically rather than by recency. Manual rearrangement would also be nice, though wholly uneccessary.

**Comment by mDibyo** [comment]
Thanks for the feedback! Alphabetical sorting makes a lot of sense. Being able to rearrange would be nice, but would be harder to implement.

Will add alphabetical sorting!
